# Generated by Django 4.1.1 on 2022-09-07 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0004_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_number', models.IntegerField(verbose_name=((1, 'Trening pierwszy'), (2, 'Trening drugi'), (3, 'Trening trzeci'), (4, 'Trening czwarty')))),
                ('series', models.IntegerField()),
                ('repeat', models.IntegerField(null=True)),
                ('TUT', models.CharField(max_length=7)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.exercises')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercises',
            name='plan',
            field=models.ManyToManyField(through='management_app.PlanExercises', to=settings.AUTH_USER_MODEL),
        ),
    ]
