# Generated by Django 4.1.1 on 2022-09-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0006_remove_user_name_remove_user_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
            ],
        ),
    ]
