# Generated by Django 4.1.1 on 2022-09-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0007_practicaltips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planexercises',
            name='TUT',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
